projects:
  amplifyDemoMopcon:
    schemaPath: amplify/backend/api/amplifyDemoMopcon/build/schema.graphql
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/API.service.service.ts
        docsFilePath: src/graphql
        region: ap-northeast-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
