// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:8f98e91d-da36-4a40-a939-8ac4318c2716",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_oP5SnScwE",
    "aws_user_pools_web_client_id": "5slihhfcjogji7sm6kqmbv8cuh",
    "oauth": {},
    "aws_content_delivery_bucket": "amplify-demo-mopcon-20191017043916-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "ap-northeast-1",
    "aws_content_delivery_url": "https://d28zcaspdypatg.cloudfront.net",
    "aws_appsync_graphqlEndpoint": "https://paetgaef3rempgcs7ayup5x3ti.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5nxvd3qoizepvoaahtev3anxsu",
    "predictions": {
        "identify": {
            "identifyLabels": {
                "proxy": false,
                "region": "ap-northeast-1",
                "defaults": {
                    "type": "LABELS"
                }
            }
        }
    },
    "aws_user_files_s3_bucket": "amplify-demo-mopcon0dbbbb668e114d3f8a4f4f35dd7aecb9-dev",
    "aws_user_files_s3_bucket_region": "ap-northeast-1"
};


export default awsmobile;
